apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplewebdemo
spec:
  replicas: 3
  selector:
   matchLabels:
    app: samplewebdemo
  template:
    metadata:
      labels:
        app: samplewebdemo
    spec:
      containers:
      - name: samplewebdemo
        image: srinivasan84/tomcatsampleweb:tagversion
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: samplewebdemo-svc
  labels:
    app: samplewebdemo
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
  selector:
    app: samplewebdemo